title: Johann Petrak
description: Homepage of Johann Petrak
theme: jekyll-theme-hacker

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  # default:
  # syntax_highlighter: coderay 
### markdown:            maruku

exclude:
- Gemfile
- Gemfile.lock
- deploy.sh
- stop.sh

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
  # - jemoji
  # see https://github.com/benbalter/jekyll-optional-front-matter
  # Note: the github-pages gem automatically includes this!
  # - jekyll-optional-front-matter  

optional_front_matter:
  enabled: true

optional_front_matter:
  remove_originals: true


